import {
    FileText, BookOpen, Video, Heart, Home, Stethoscope, Activity,
    AlertCircle, Award, Bandage, Brain, Briefcase, Calendar, Check,
    ClipboardList, Clock, Droplet, Eye, FileCheck, Folder,
    GraduationCap, Hand, HeartPulse, HelpCircle, Hospital, Leaf,
    LifeBuoy, MapPin, MessageCircle, Phone, Pill, Plus, Shield,
    Star, Thermometer, User, Users, Wrench, Zap, Accessibility,
    Baby, Bath, Bed, Bone, CircleCheck, Cross, Fingerprint, Flame,
    Footprints, Gauge, Glasses, Globe, Hammer, Headphones,
    HeartHandshake, Info, Lightbulb, Link, Lock, Mail, Megaphone,
    Microscope, Moon, Palette, Paperclip, PenTool, Percent, PersonStanding,
    Podcast, Puzzle, Radio, Ribbon, Rocket, Scale, Search, Settings,
    Share, ShieldCheck, Sparkles, Syringe, Target, Truck, Umbrella,
    Verified, Wallet, Waves, Wifi, Wind, Scissors, Layers, type LucideIcon
} from "lucide-react";

export interface IconOption {
    name: string;
    icon: LucideIcon;
}

export const iconOptions: IconOption[] = [
    { name: "FileText", icon: FileText },
    { name: "BookOpen", icon: BookOpen },
    { name: "Video", icon: Video },
    { name: "Heart", icon: Heart },
    { name: "Home", icon: Home },
    { name: "Stethoscope", icon: Stethoscope },
    { name: "Activity", icon: Activity },
    { name: "AlertCircle", icon: AlertCircle },
    { name: "Award", icon: Award },
    { name: "Bandage", icon: Bandage },
    { name: "Brain", icon: Brain },
    { name: "Briefcase", icon: Briefcase },
    { name: "Calendar", icon: Calendar },
    { name: "Check", icon: Check },
    { name: "ClipboardList", icon: ClipboardList },
    { name: "Clock", icon: Clock },
    { name: "Droplet", icon: Droplet },
    { name: "Eye", icon: Eye },
    { name: "FileCheck", icon: FileCheck },
    { name: "Folder", icon: Folder },
    { name: "GraduationCap", icon: GraduationCap },
    { name: "Hand", icon: Hand },
    { name: "HeartPulse", icon: HeartPulse },
    { name: "HelpCircle", icon: HelpCircle },
    { name: "Hospital", icon: Hospital },
    { name: "Leaf", icon: Leaf },
    { name: "LifeBuoy", icon: LifeBuoy },
    { name: "MapPin", icon: MapPin },
    { name: "MessageCircle", icon: MessageCircle },
    { name: "Phone", icon: Phone },
    { name: "Pill", icon: Pill },
    { name: "Plus", icon: Plus },
    { name: "Shield", icon: Shield },
    { name: "Star", icon: Star },
    { name: "Thermometer", icon: Thermometer },
    { name: "User", icon: User },
    { name: "Users", icon: Users },
    { name: "Wrench", icon: Wrench },
    { name: "Zap", icon: Zap },
    { name: "Accessibility", icon: Accessibility },
    { name: "Baby", icon: Baby },
    { name: "Bath", icon: Bath },
    { name: "Bed", icon: Bed },
    { name: "Bone", icon: Bone },
    { name: "CircleCheck", icon: CircleCheck },
    { name: "Cross", icon: Cross },
    { name: "Fingerprint", icon: Fingerprint },
    { name: "Flame", icon: Flame },
    { name: "Footprints", icon: Footprints },
    { name: "Gauge", icon: Gauge },
    { name: "Glasses", icon: Glasses },
    { name: "Globe", icon: Globe },
    { name: "Hammer", icon: Hammer },
    { name: "Headphones", icon: Headphones },
    { name: "HeartHandshake", icon: HeartHandshake },
    { name: "Info", icon: Info },
    { name: "Lightbulb", icon: Lightbulb },
    { name: "Link", icon: Link },
    { name: "Lock", icon: Lock },
    { name: "Mail", icon: Mail },
    { name: "Megaphone", icon: Megaphone },
    { name: "Microscope", icon: Microscope },
    { name: "Moon", icon: Moon },
    { name: "Palette", icon: Palette },
    { name: "Paperclip", icon: Paperclip },
    { name: "PenTool", icon: PenTool },
    { name: "Percent", icon: Percent },
    { name: "PersonStanding", icon: PersonStanding },
    { name: "Podcast", icon: Podcast },
    { name: "Puzzle", icon: Puzzle },
    { name: "Radio", icon: Radio },
    { name: "Ribbon", icon: Ribbon },
    { name: "Rocket", icon: Rocket },
    { name: "Scale", icon: Scale },
    { name: "Search", icon: Search },
    { name: "Settings", icon: Settings },
    { name: "Share", icon: Share },
    { name: "ShieldCheck", icon: ShieldCheck },
    { name: "Sparkles", icon: Sparkles },
    { name: "Syringe", icon: Syringe },
    { name: "Target", icon: Target },
    { name: "Truck", icon: Truck },
    { name: "Umbrella", icon: Umbrella },
    { name: "Verified", icon: Verified },
    { name: "Wallet", icon: Wallet },
    { name: "Waves", icon: Waves },
    { name: "Wifi", icon: Wifi },
    { name: "Wind", icon: Wind },
    { name: "Scissors", icon: Scissors },
    { name: "Layers", icon: Layers },
];

export const getIconByName = (name: string): LucideIcon => {
    const option = iconOptions.find(opt => opt.name === name);
    return option ? option.icon : Heart; // Default to Heart if not found
};
