// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbxushxguflleynhrpmw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtieHVzaHhndWZsbGV5bmhycG13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU2OTYzNzksImV4cCI6MjA4MTI3MjM3OX0.lP1WwywVHqbHax4E0QwTkkPIh8_nqJlmuy9dbJ91E9w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});